const std = @import("std");
const builtin = @import("builtin");

const c = @cImport({
    switch (builtin.target.os.tag) {
        .linux => @cInclude("linux/input-event-codes.h"),
        .windows => {
            @cDefine("WINDOWS_LEAN_AND_MEAN", "");
            @cInclude("windows.h");
        },
        else => @compileError("Unsupported platform"),
    }
});

const LayoutLabelsLookupKV = struct { []const u8, usize };

const layout_labels_lookup_slice = blk: {
    if (builtin.os.tag == .linux) { const l = [_]LayoutLabelsLookupKV{
        // zig fmt: off
        .{ "KC_NO",                  c.KEY_RESERVED },
        .{ "KC_TRANSPARENT",         c.KEY_RESERVED },
        .{ "KC_A",                   c.KEY_A },
        .{ "KC_B",                   c.KEY_B },
        .{ "KC_C",                   c.KEY_C },
        .{ "KC_D",                   c.KEY_D },
        .{ "KC_E",                   c.KEY_E },
        .{ "KC_F",                   c.KEY_F },
        .{ "KC_G",                   c.KEY_G },
        .{ "KC_H",                   c.KEY_H },
        .{ "KC_I",                   c.KEY_I },
        .{ "KC_J",                   c.KEY_J },
        .{ "KC_K",                   c.KEY_K },
        .{ "KC_L",                   c.KEY_L },
        .{ "KC_M",                   c.KEY_M },
        .{ "KC_N",                   c.KEY_N },
        .{ "KC_O",                   c.KEY_O },
        .{ "KC_P",                   c.KEY_P },
        .{ "KC_Q",                   c.KEY_Q },
        .{ "KC_R",                   c.KEY_R },
        .{ "KC_S",                   c.KEY_S },
        .{ "KC_T",                   c.KEY_T },
        .{ "KC_U",                   c.KEY_U },
        .{ "KC_V",                   c.KEY_V },
        .{ "KC_W",                   c.KEY_W },
        .{ "KC_X",                   c.KEY_X },
        .{ "KC_Y",                   c.KEY_Y },
        .{ "KC_Z",                   c.KEY_Z },
        .{ "KC_1",                   c.KEY_1 },
        .{ "KC_2",                   c.KEY_2 },
        .{ "KC_3",                   c.KEY_3 },
        .{ "KC_4",                   c.KEY_4 },
        .{ "KC_5",                   c.KEY_5 },
        .{ "KC_6",                   c.KEY_6 },
        .{ "KC_7",                   c.KEY_7 },
        .{ "KC_8",                   c.KEY_8 },
        .{ "KC_9",                   c.KEY_9 },
        .{ "KC_0",                   c.KEY_0 },
        .{ "KC_ENTER",               c.KEY_ENTER },            .{ "KC_ENT",  c.KEY_ENTER },      .{ "KC_RETURN", c.KEY_ENTER },    .{ "KC_RETN", c.KEY_ENTER },
        .{ "KC_ESCAPE",              c.KEY_ESC },              .{ "KC_ESC",  c.KEY_ESC },
        .{ "KC_BACKSPACE",           c.KEY_BACKSPACE },        .{ "KC_BSPC", c.KEY_BACKSPACE },
        .{ "KC_TAB",                 c.KEY_TAB },
        .{ "KC_SPACE",               c.KEY_SPACE },            .{ "KC_SPC",  c.KEY_SPACE },
        .{ "KC_MINUS",               c.KEY_MINUS },            .{ "KC_MINS", c.KEY_MINUS },
        .{ "KC_EQUAL",               c.KEY_EQUAL },            .{ "KC_EQL",  c.KEY_EQUAL },
        .{ "KC_LEFT_BRACKET",        c.KEY_LEFTBRACE },        .{ "KC_LBRC", c.KEY_LEFTBRACE },
        .{ "KC_RIGHT_BRACKET",       c.KEY_RIGHTBRACE },       .{ "KC_RBRC", c.KEY_RIGHTBRACE },
        .{ "KC_BACKSLASH",           c.KEY_BACKSLASH },        .{ "KC_BSLS", c.KEY_BACKSLASH },
        .{ "KC_NONUS_HASH",          c.KEY_102ND },            .{ "KC_NUHS", c.KEY_102ND },
        .{ "KC_SEMICOLON",           c.KEY_SEMICOLON },        .{ "KC_SCLN", c.KEY_SEMICOLON },
        .{ "KC_QUOTE",               c.KEY_APOSTROPHE },       .{ "KC_QUOT", c.KEY_APOSTROPHE },
        .{ "KC_GRAVE",               c.KEY_GRAVE },            .{ "KC_GRV",  c.KEY_GRAVE },
        .{ "KC_COMMA",               c.KEY_COMMA },            .{ "KC_COMM", c.KEY_COMMA },
        .{ "KC_DOT",                 c.KEY_DOT },
        .{ "KC_SLASH",               c.KEY_SLASH },            .{ "KC_SLSH", c.KEY_SLASH },
        .{ "KC_CAPS_LOCK",           c.KEY_CAPSLOCK },         .{ "KC_CAPS", c.KEY_CAPSLOCK },
        .{ "KC_F1",                  c.KEY_F1 },
        .{ "KC_F2",                  c.KEY_F2 },
        .{ "KC_F3",                  c.KEY_F3 },
        .{ "KC_F4",                  c.KEY_F4 },
        .{ "KC_F5",                  c.KEY_F5 },
        .{ "KC_F6",                  c.KEY_F6 },
        .{ "KC_F7",                  c.KEY_F7 },
        .{ "KC_F8",                  c.KEY_F8 },
        .{ "KC_F9",                  c.KEY_F9 },
        .{ "KC_F10",                 c.KEY_F10 },
        .{ "KC_F11",                 c.KEY_F11 },
        .{ "KC_F12",                 c.KEY_F12 },
        .{ "KC_PRINT_SCREEN",        c.KEY_SYSRQ },            .{ "KC_PSCR", c.KEY_SYSRQ },
        .{ "KC_SCROLL_LOCK",         c.KEY_SCREENLOCK },       .{ "KC_SCRL", c.KEY_SCROLLLOCK }, .{ "KC_BRMD", c.KEY_SCREENLOCK },
        .{ "KC_PAUSE",               c.KEY_PAUSE },            .{ "KC_PAUS", c.KEY_PAUSE },      .{ "KC_BRK",  c.KEY_PAUSE },      .{ "KC_BRMU", c.KEY_PAUSE },
        .{ "KC_INSERT",              c.KEY_INSERT },           .{ "KC_INS",  c.KEY_INSERT },
        .{ "KC_HOME",                c.KEY_HOME },
        .{ "KC_PAGE_UP",             c.KEY_PAGEUP },           .{ "KC_PGUP", c.KEY_PAGEUP },
        .{ "KC_DELETE",              c.KEY_DELETE },           .{ "KC_DEL",  c.KEY_DELETE },
        .{ "KC_END",                 c.KEY_END },
        .{ "KC_PAGE_DOWN",           c.KEY_PAGEDOWN },         .{ "KC_PGDN", c.KEY_PAGEDOWN },
        .{ "KC_RIGHT",               c.KEY_RIGHT },            .{ "KC_RGHT", c.KEY_RIGHT },
        .{ "KC_LEFT",                c.KEY_LEFT },
        .{ "KC_DOWN",                c.KEY_DOWN },
        .{ "KC_UP",                  c.KEY_UP },
        .{ "KC_NUM_LOCK",            c.KEY_NUMLOCK },          .{ "KC_NUM",  c.KEY_NUMLOCK },
        .{ "KC_KP_SLASH",            c.KEY_KPSLASH },          .{ "KC_PSLS", c.KEY_KPSLASH },
        .{ "KC_KP_ASTERISK",         c.KEY_KPASTERISK },       .{ "KC_PAST", c.KEY_KPASTERISK },
        .{ "KC_KP_MINUS",            c.KEY_KPMINUS },          .{ "KC_PMNS", c.KEY_KPMINUS },
        .{ "KC_KP_PLUS",             c.KEY_KPPLUS },           .{ "KC_PPLS", c.KEY_KPPLUS },
        .{ "KC_KP_ENTER",            c.KEY_KPENTER },          .{ "KC_PENT", c.KEY_KPENTER },
        .{ "KC_KP_1",                c.KEY_KP1 },              .{ "KC_P1",   c.KEY_KP1 },
        .{ "KC_KP_2",                c.KEY_KP2 },              .{ "KC_P2",   c.KEY_KP2 },
        .{ "KC_KP_3",                c.KEY_KP3 },              .{ "KC_P3",   c.KEY_KP3 },
        .{ "KC_KP_4",                c.KEY_KP4 },              .{ "KC_P4",   c.KEY_KP4 },
        .{ "KC_KP_5",                c.KEY_KP5 },              .{ "KC_P5",   c.KEY_KP5 },
        .{ "KC_KP_6",                c.KEY_KP6 },              .{ "KC_P6",   c.KEY_KP6 },
        .{ "KC_KP_7",                c.KEY_KP7 },              .{ "KC_P7",   c.KEY_KP7 },
        .{ "KC_KP_8",                c.KEY_KP8 },              .{ "KC_P8",   c.KEY_KP8 },
        .{ "KC_KP_9",                c.KEY_KP9 },              .{ "KC_P9",   c.KEY_KP9 },
        .{ "KC_KP_0",                c.KEY_KP0 },              .{ "KC_P0",   c.KEY_KP0 },
        .{ "KC_KP_DOT",              c.KEY_KPDOT },            .{ "KC_PDOT", c.KEY_KPDOT },
        .{ "KC_NONUS_BACKSLASH",     c.KEY_BACKSLASH },        .{ "KC_NUBS", c.KEY_BACKSLASH },
        .{ "KC_APPLICATION",         c.KEY_COMPOSE },          .{ "KC_APP",  c.KEY_COMPOSE },
        .{ "KC_KB_POWER",            0 },
        .{ "KC_KP_EQUAL",            c.KEY_KPEQUAL },          .{ "KC_PEQL", c.KEY_KPEQUAL },
        .{ "KC_F13",                 c.KEY_F13 },
        .{ "KC_F14",                 c.KEY_F14 },
        .{ "KC_F15",                 c.KEY_F15 },
        .{ "KC_F16",                 c.KEY_F16 },
        .{ "KC_F17",                 c.KEY_F17 },
        .{ "KC_F18",                 c.KEY_F18 },
        .{ "KC_F19",                 c.KEY_F19 },
        .{ "KC_F20",                 c.KEY_F20 },
        .{ "KC_F21",                 c.KEY_F21 },
        .{ "KC_F22",                 c.KEY_F22 },
        .{ "KC_F23",                 c.KEY_F23 },
        .{ "KC_F24",                 c.KEY_F24 },
        .{ "KC_EXECUTE",             0 },                      .{ "KC_EXEC", 0 },
        .{ "KC_HELP",                c.KEY_HELP },
        .{ "KC_MENU",                c.KEY_MENU },
        .{ "KC_SELECT",              c.KEY_SELECT },           .{ "KC_SLCT", c.KEY_SELECT },
        .{ "KC_STOP",                c.KEY_STOP },
        .{ "KC_AGAIN",               c.KEY_AGAIN },            .{ "KC_AGIN", c.KEY_AGAIN },
        .{ "KC_UNDO",                c.KEY_UNDO },
        .{ "KC_CUT",                 c.KEY_CUT },
        .{ "KC_COPY",                c.KEY_COPY },
        .{ "KC_PASTE",               c.KEY_PASTE },            .{ "KC_PSTE", c.KEY_PASTE },
        .{ "KC_FIND",                c.KEY_FIND },
        .{ "KC_KB_MUTE",             c.KEY_MUTE },
        .{ "KC_KB_VOLUME_UP",        c.KEY_VOLUMEUP },
        .{ "KC_KB_VOLUME_DOWN",      c.KEY_VOLUMEDOWN },
        .{ "KC_LOCKING_CAPS_LOCK",   0 },                      .{ "KC_LCAP", 0 },
        .{ "KC_LOCKING_NUM_LOCK",    0 },                      .{ "KC_LNUM", 0 },
        .{ "KC_LOCKING_SCROLL_LOCK", 0 },                      .{ "KC_LSCR", 0 },
        .{ "KC_KP_COMMA",            c.KEY_KPCOMMA },          .{ "KC_PCMM", c.KEY_KPCOMMA },
        .{ "KC_KP_EQUAL_AS400",      0 },
        .{ "KC_INTERNATIONAL_1",     c.KEY_RO },               .{ "KC_INT1", c.KEY_RO },
        .{ "KC_INTERNATIONAL_2",     c.KEY_KATAKANAHIRAGANA }, .{ "KC_INT2", c.KEY_KATAKANAHIRAGANA },
        .{ "KC_INTERNATIONAL_3",     c.KEY_YEN },              .{ "KC_INT3", c.KEY_YEN },
        .{ "KC_INTERNATIONAL_4",     c.KEY_HENKAN },           .{ "KC_INT4", c.KEY_HENKAN },
        .{ "KC_INTERNATIONAL_5",     c.KEY_MUHENKAN },         .{ "KC_INT5", c.KEY_MUHENKAN },
        .{ "KC_INTERNATIONAL_6",     c.KEY_KPJPCOMMA },        .{ "KC_INT6", c.KEY_KPJPCOMMA },
        .{ "KC_INTERNATIONAL_7",     0 },
        .{ "KC_INTERNATIONAL_8",     0 },
        .{ "KC_INTERNATIONAL_9",     0 },
        .{ "KC_LANGUAGE_1",          c.KEY_HANGEUL },          .{ "KC_LNG1", c.KEY_HANGEUL },
        .{ "KC_LANGUAGE_2",          c.KEY_HANJA },            .{ "KC_LNG2", c.KEY_HANJA },
        .{ "KC_LANGUAGE_3",          c.KEY_KATAKANA },         .{ "KC_LNG3", c.KEY_KATAKANA },
        .{ "KC_LANGUAGE_4",          c.KEY_HIRAGANA },         .{ "KC_LNG4", c.KEY_HIRAGANA },
        .{ "KC_LANGUAGE_5",          c.KEY_ZENKAKUHANKAKU },   .{ "KC_LNG5", c.KEY_ZENKAKUHANKAKU },
        .{ "KC_LANGUAGE_6",          0 },
        .{ "KC_LANGUAGE_7",          0 },
        .{ "KC_LANGUAGE_8",          0 },
        .{ "KC_LANGUAGE_9",          0 },
        .{ "KC_ALTERNATE_ERASE",     0 },                      .{ "KC_ERAS", 0 },
        .{ "KC_SYSTEM_REQUEST",      c.KEY_SYSRQ },            .{ "KC_SYRQ", c.KEY_SYSRQ },
        .{ "KC_CANCEL",              0 },                      .{ "KC_CNCL", 0 },
        .{ "KC_CLEAR",               c.KEY_CLEAR },            .{ "KC_CLR",  c.KEY_CLEAR },
        .{ "KC_PRIOR",               0 },                      .{ "KC_PRIR", 0 },
        .{ "KC_SEPARATOR",           0 },                      .{ "KC_SEPR", 0 },
        .{ "KC_OUT",                 0 },
        .{ "KC_OPER",                0 },
        .{ "KC_CLEAR_AGAIN",         0 },                      .{ "KC_CLAG", 0 },
        .{ "KC_CRSEL",               0 },                      .{ "KC_CRSL", 0 },
        .{ "KC_EXSEL",               0 },                      .{ "KC_EXSL", 0 },
        .{ "KC_SYSTEM_POWER",        c.KEY_POWER },            .{ "KC_PWR",  c.KEY_POWER },
        .{ "KC_SYSTEM_SLEEP",        c.KEY_SLEEP },            .{ "KC_SLEP", c.KEY_SLEEP },
        .{ "KC_SYSTEM_WAKE",         c.KEY_WAKEUP },           .{ "KC_WAKE", c.KEY_WAKEUP },
        .{ "KC_AUDIO_MUTE",          c.KEY_MUTE },             .{ "KC_MUTE", c.KEY_MUTE },
        .{ "KC_AUDIO_VOL_UP",        c.KEY_VOLUMEUP },         .{ "KC_VOLU", c.KEY_VOLUMEUP },
        .{ "KC_AUDIO_VOL_DOWN",      c.KEY_VOLUMEDOWN },       .{ "KC_VOLD", c.KEY_VOLUMEDOWN },
        .{ "KC_MEDIA_NEXT_TRACK",    c.KEY_NEXTSONG },         .{ "KC_MNXT", c.KEY_NEXTSONG },
        .{ "KC_MEDIA_PREV_TRACK",    c.KEY_PREVIOUSSONG },     .{ "KC_MPRV", c.KEY_PREVIOUSSONG },
        .{ "KC_MEDIA_STOP",          c.KEY_STOPCD },           .{ "KC_MSTP", c.KEY_STOPCD },
        .{ "KC_MEDIA_PLAY_PAUSE",    c.KEY_PLAYPAUSE },        .{ "KC_MPLY", c.KEY_PLAYPAUSE },
        .{ "KC_MEDIA_SELECT",        0 },                      .{ "KC_MSEL", 0 },
        .{ "KC_MEDIA_EJECT",         c.KEY_EJECTCD },          .{ "KC_EJCT", c.KEY_EJECTCD },
        .{ "KC_MAIL",                c.KEY_MAIL },
        .{ "KC_CALCULATOR",          c.KEY_CALC },             .{ "KC_CALC", c.KEY_CALC },
        .{ "KC_MY_COMPUTER",         c.KEY_COMPUTER },         .{ "KC_MYCM", c.KEY_COMPUTER },
        .{ "KC_WWW_SEARCH",          c.KEY_FIND },             .{ "KC_WSCH", c.KEY_FIND },
        .{ "KC_WWW_HOME",            c.KEY_HOMEPAGE },         .{ "KC_WHOM", c.KEY_HOMEPAGE },
        .{ "KC_WWW_BACK",            c.KEY_BACK },             .{ "KC_WBAK", c.KEY_BACK },
        .{ "KC_WWW_FORWARD",         c.KEY_FORWARD },          .{ "KC_WFWD", c.KEY_FORWARD },
        .{ "KC_WWW_STOP",            c.KEY_STOP },             .{ "KC_WSTP", c.KEY_STOP },
        .{ "KC_WWW_REFRESH",         c.KEY_REFRESH },          .{ "KC_WREF", c.KEY_REFRESH },
        .{ "KC_WWW_FAVORITES",       c.KEY_BOOKMARKS },        .{ "KC_WFAV", c.KEY_BOOKMARKS },
        .{ "KC_MEDIA_FAST_FORWARD",  c.KEY_FASTFORWARD },      .{ "KC_MFFD", c.KEY_FASTFORWARD },
        .{ "KC_MEDIA_REWIND",        0 },                      .{ "KC_MRWD", 0 },
        .{ "KC_BRIGHTNESS_UP",       c.KEY_BRIGHTNESSUP },     .{ "KC_BRIU", c.KEY_BRIGHTNESSUP },
        .{ "KC_BRIGHTNESS_DOWN",     c.KEY_BRIGHTNESSDOWN },   .{ "KC_BRID", c.KEY_BRIGHTNESSDOWN },
        .{ "KC_CONTROL_PANEL",       0 },                      .{ "KC_CPNL", 0 },
        .{ "KC_ASSISTANT",           0 },                      .{ "KC_ASST", 0 },
        .{ "KC_MISSION_CONTROL",     0 },                      .{ "KC_MCTL", 0 },
        .{ "KC_LAUNCHPAD",           0 },                      .{ "KC_LPAD", 0 },
        .{ "KC_LEFT_CTRL",           c.KEY_LEFTCTRL },         .{ "KC_LCTL", c.KEY_LEFTCTRL },
        .{ "KC_LEFT_SHIFT",          c.KEY_LEFTSHIFT },        .{ "KC_LSFT", c.KEY_LEFTSHIFT },
        .{ "KC_LEFT_ALT",            c.KEY_LEFTALT },          .{ "KC_LALT", c.KEY_LEFTALT },    .{ "KC_LOPT", c.KEY_LEFTALT },
        .{ "KC_LEFT_GUI",            c.KEY_LEFTMETA },         .{ "KC_LGUI", c.KEY_LEFTMETA },   .{ "KC_LCMD", c.KEY_LEFTMETA },   .{ "KC_LWIN", c.KEY_LEFTMETA },
        .{ "KC_RIGHT_CTRL",          c.KEY_RIGHTCTRL },        .{ "KC_RCTL", c.KEY_RIGHTCTRL },
        .{ "KC_RIGHT_SHIFT",         c.KEY_RIGHTSHIFT },       .{ "KC_RSFT", c.KEY_RIGHTSHIFT },
        .{ "KC_RIGHT_ALT",           c.KEY_RIGHTALT },         .{ "KC_RALT", c.KEY_RIGHTALT },   .{ "KC_ROPT", c.KEY_RIGHTALT },   .{ "KC_ALGR", c.KEY_RIGHTALT },
        .{ "KC_RIGHT_GUI",           c.KEY_RIGHTMETA },        .{ "KC_RGUI", c.KEY_RIGHTMETA },  .{ "KC_RCMD", c.KEY_RIGHTMETA },  .{ "KC_RWIN", c.KEY_RIGHTMETA },
        // zig fmt: on
    };
    break :blk l;
    }
    else if (builtin.os.tag == .windows) { const l = [_]LayoutLabelsLookupKV{
        // zig fmt: off
        .{ "KC_NO",                  0 },
        .{ "KC_TRANSPARENT",         0 },
        .{ "KC_A",                   0x41 },
        .{ "KC_B",                   0x42 },
        .{ "KC_C",                   0x43 },
        .{ "KC_D",                   0x44 },
        .{ "KC_E",                   0x45 },
        .{ "KC_F",                   0x46 },
        .{ "KC_G",                   0x47 },
        .{ "KC_H",                   0x48 },
        .{ "KC_I",                   0x49 },
        .{ "KC_J",                   0x4A },
        .{ "KC_K",                   0x4B },
        .{ "KC_L",                   0x4C },
        .{ "KC_M",                   0x4D },
        .{ "KC_N",                   0x4E },
        .{ "KC_O",                   0x4F },
        .{ "KC_P",                   0x50 },
        .{ "KC_Q",                   0x51 },
        .{ "KC_R",                   0x52 },
        .{ "KC_S",                   0x53 },
        .{ "KC_T",                   0x54 },
        .{ "KC_U",                   0x55 },
        .{ "KC_V",                   0x56 },
        .{ "KC_W",                   0x57 },
        .{ "KC_X",                   0x58 },
        .{ "KC_Y",                   0x59 },
        .{ "KC_Z",                   0x5A },
        .{ "KC_1",                   0x31 },
        .{ "KC_2",                   0x32 },
        .{ "KC_3",                   0x33 },
        .{ "KC_4",                   0x34 },
        .{ "KC_5",                   0x35 },
        .{ "KC_6",                   0x36 },
        .{ "KC_7",                   0x37 },
        .{ "KC_8",                   0x38 },
        .{ "KC_9",                   0x39 },
        .{ "KC_0",                   0x30 },
        .{ "KC_ENTER",               c.VK_RETURN },            .{ "KC_ENT",  c.VK_RETURN },      .{ "KC_RETURN", c.VK_RETURN },    .{ "KC_RETN", c.VK_RETURN },
        .{ "KC_ESCAPE",              c.VK_ESCAPE },            .{ "KC_ESC",  c.VK_ESCAPE },
        .{ "KC_BACKSPACE",           c.VK_BACK },              .{ "KC_BSPC", c.VK_BACK },
        .{ "KC_TAB",                 c.VK_TAB },
        .{ "KC_SPACE",               c.VK_SPACE },             .{ "KC_SPC",  c.VK_SPACE },
        .{ "KC_MINUS",               c.VK_OEM_MINUS },         .{ "KC_MINS", c.VK_OEM_MINUS },
        .{ "KC_EQUAL",               c.VK_OEM_PLUS },          .{ "KC_EQL",  c.VK_OEM_PLUS },
        .{ "KC_LEFT_BRACKET",        c.VK_OEM_4 },             .{ "KC_LBRC", c.VK_OEM_4 },
        .{ "KC_RIGHT_BRACKET",       c.VK_OEM_6 },             .{ "KC_RBRC", c.VK_OEM_6 },
        .{ "KC_BACKSLASH",           c.VK_OEM_5 },             .{ "KC_BSLS", c.VK_OEM_5 },
        .{ "KC_NONUS_HASH",          c.VK_OEM_102 },           .{ "KC_NUHS", c.VK_OEM_102 },
        .{ "KC_SEMICOLON",           c.VK_OEM_1 },             .{ "KC_SCLN", c.VK_OEM_1 },
        .{ "KC_QUOTE",               c.VK_OEM_7 },             .{ "KC_QUOT", c.VK_OEM_7 },
        .{ "KC_GRAVE",               c.VK_OEM_3 },             .{ "KC_GRV",  c.VK_OEM_3 },
        .{ "KC_COMMA",               c.VK_OEM_COMMA },         .{ "KC_COMM", c.VK_OEM_COMMA },
        .{ "KC_DOT",                 c.VK_OEM_PERIOD },
        .{ "KC_SLASH",               c.VK_OEM_2 },             .{ "KC_SLSH", c.VK_OEM_2 },
        .{ "KC_CAPS_LOCK",           c.VK_CAPITAL },           .{ "KC_CAPS", c.VK_CAPITAL },
        .{ "KC_F1",                  c.VK_F1 },
        .{ "KC_F2",                  c.VK_F2 },
        .{ "KC_F3",                  c.VK_F3 },
        .{ "KC_F4",                  c.VK_F4 },
        .{ "KC_F5",                  c.VK_F5 },
        .{ "KC_F6",                  c.VK_F6 },
        .{ "KC_F7",                  c.VK_F7 },
        .{ "KC_F8",                  c.VK_F8 },
        .{ "KC_F9",                  c.VK_F9 },
        .{ "KC_F10",                 c.VK_F10 },
        .{ "KC_F11",                 c.VK_F11 },
        .{ "KC_F12",                 c.VK_F12 },
        .{ "KC_PRINT_SCREEN",        c.VK_SNAPSHOT },          .{ "KC_PSCR", c.VK_SNAPSHOT },
        .{ "KC_SCROLL_LOCK",         c.VK_SCROLL },            .{ "KC_SCRL", c.VK_SCROLL },      .{ "KC_BRMD", c.VK_SCROLL },
        .{ "KC_PAUSE",               c.VK_PAUSE } ,            .{ "KC_PAUS", c.VK_PAUSE },       .{ "KC_BRK",  c.VK_PAUSE },      .{ "KC_BRMU", c.VK_PAUSE },
        .{ "KC_INSERT",              c.VK_INSERT },            .{ "KC_INS",  c.VK_INSERT },
        .{ "KC_HOME",                c.VK_HOME },
        .{ "KC_PAGE_UP",             c.VK_PRIOR },             .{ "KC_PGUP", c.VK_PRIOR },
        .{ "KC_DELETE",              c.VK_DELETE },            .{ "KC_DEL",  c.VK_DELETE },
        .{ "KC_END",                 c.VK_END },
        .{ "KC_PAGE_DOWN",           c.VK_NEXT },              .{ "KC_PGDN", c.VK_NEXT },
        .{ "KC_RIGHT",               c.VK_RIGHT },             .{ "KC_RGHT", c.VK_RIGHT },
        .{ "KC_LEFT",                c.VK_LEFT },
        .{ "KC_DOWN",                c.VK_DOWN },
        .{ "KC_UP",                  c.VK_UP },
        .{ "KC_NUM_LOCK",            c.VK_NUMLOCK },           .{ "KC_NUM",  c.VK_NUMLOCK },
        .{ "KC_KP_SLASH",            c.VK_DIVIDE },            .{ "KC_PSLS", c.VK_DIVIDE },
        .{ "KC_KP_ASTERISK",         c.VK_MULTIPLY },          .{ "KC_PAST", c.VK_MULTIPLY },
        .{ "KC_KP_MINUS",            c.VK_SUBTRACT },          .{ "KC_PMNS", c.VK_SUBTRACT },
        .{ "KC_KP_PLUS",             c.VK_ADD },               .{ "KC_PPLS", c.VK_ADD },
        .{ "KC_KP_ENTER",            0 },                      .{ "KC_PENT", 0 },
        .{ "KC_KP_1",                c.VK_NUMPAD1 },           .{ "KC_P1", c.VK_NUMPAD1 },
        .{ "KC_KP_2",                c.VK_NUMPAD2 },           .{ "KC_P2", c.VK_NUMPAD2 },
        .{ "KC_KP_3",                c.VK_NUMPAD3 },           .{ "KC_P3", c.VK_NUMPAD3 },
        .{ "KC_KP_4",                c.VK_NUMPAD4 },           .{ "KC_P4", c.VK_NUMPAD4 },
        .{ "KC_KP_5",                c.VK_NUMPAD5 },           .{ "KC_P5", c.VK_NUMPAD5 },
        .{ "KC_KP_6",                c.VK_NUMPAD6 },           .{ "KC_P6", c.VK_NUMPAD6 },
        .{ "KC_KP_7",                c.VK_NUMPAD7 },           .{ "KC_P7", c.VK_NUMPAD7 },
        .{ "KC_KP_8",                c.VK_NUMPAD8 },           .{ "KC_P8", c.VK_NUMPAD8 },
        .{ "KC_KP_9",                c.VK_NUMPAD9 },           .{ "KC_P9", c.VK_NUMPAD9 },
        .{ "KC_KP_0",                c.VK_NUMPAD0 },           .{ "KC_P0", c.VK_NUMPAD0 },
        .{ "KC_KP_DOT",              c.VK_DECIMAL },           .{ "KC_PDOT", c.VK_DECIMAL },
        .{ "KC_NONUS_BACKSLASH",     0 },                      .{ "KC_NUBS", 0 },
        .{ "KC_APPLICATION",         0 },                      .{ "KC_APP", 0 },
        .{ "KC_KB_POWER",            0 },
        .{ "KC_KP_EQUAL",            0 },                      .{ "KC_PEQL", 0 },
        .{ "KC_F13",                 c.VK_F13 },
        .{ "KC_F14",                 c.VK_F14 },
        .{ "KC_F15",                 c.VK_F15 },
        .{ "KC_F16",                 c.VK_F16 },
        .{ "KC_F17",                 c.VK_F17 },
        .{ "KC_F18",                 c.VK_F18 },
        .{ "KC_F19",                 c.VK_F19 },
        .{ "KC_F20",                 c.VK_F20 },
        .{ "KC_F21",                 c.VK_F21 },
        .{ "KC_F22",                 c.VK_F22 },
        .{ "KC_F23",                 c.VK_F23 },
        .{ "KC_F24",                 c.VK_F24 },
        .{ "KC_EXECUTE",             c.VK_EXECUTE },           .{ "KC_EXEC", c.VK_EXECUTE },
        .{ "KC_HELP",                c.VK_HELP },
        .{ "KC_MENU",                c.VK_MENU },
        .{ "KC_SELECT",              c.VK_SELECT},             .{ "KC_SLCT", c.VK_SELECT },
        .{ "KC_STOP",                0 },
        .{ "KC_AGAIN",               0 },                      .{ "KC_AGIN", 0 },
        .{ "KC_UNDO",                0 },
        .{ "KC_CUT",                 0 },
        .{ "KC_COPY",                0 },
        .{ "KC_PASTE",               0 },                      .{ "KC_PSTE", 0 },
        .{ "KC_FIND",                0 },
        .{ "KC_KB_MUTE",             c.VK_VOLUME_MUTE },
        .{ "KC_KB_VOLUME_UP",        c.VK_VOLUME_UP },
        .{ "KC_KB_VOLUME_DOWN",      c.VK_VOLUME_DOWN },
        .{ "KC_LOCKING_CAPS_LOCK",   0 },                      .{ "KC_LCAP", 0 },
        .{ "KC_LOCKING_NUM_LOCK",    0 },                      .{ "KC_LNUM", 0 },
        .{ "KC_LOCKING_SCROLL_LOCK", 0 },                      .{ "KC_LSCR", 0 },
        .{ "KC_KP_COMMA",            0 },                      .{ "KC_PCMM", 0 },
        .{ "KC_KP_EQUAL_AS400",      0 },
        .{ "KC_INTERNATIONAL_1",     0 },                      .{ "KC_INT1", 0 },
        .{ "KC_INTERNATIONAL_2",     0 },                      .{ "KC_INT2", 0 },
        .{ "KC_INTERNATIONAL_3",     0 },                      .{ "KC_INT3", 0 },
        .{ "KC_INTERNATIONAL_4",     0 },                      .{ "KC_INT4", 0 },
        .{ "KC_INTERNATIONAL_5",     0 },                      .{ "KC_INT5", 0 },
        .{ "KC_INTERNATIONAL_6",     0 },                      .{ "KC_INT6", 0 },
        .{ "KC_INTERNATIONAL_7",     0 },
        .{ "KC_INTERNATIONAL_8",     0 },
        .{ "KC_INTERNATIONAL_9",     0 },
        .{ "KC_LANGUAGE_1",          0 },                      .{ "KC_LNG1", 0 },
        .{ "KC_LANGUAGE_2",          0 },                      .{ "KC_LNG2", 0 },
        .{ "KC_LANGUAGE_3",          0 },                      .{ "KC_LNG3", 0 },
        .{ "KC_LANGUAGE_4",          0 },                      .{ "KC_LNG4", 0 },
        .{ "KC_LANGUAGE_5",          0 },                      .{ "KC_LNG5", 0 },
        .{ "KC_LANGUAGE_6",          0 },
        .{ "KC_LANGUAGE_7",          0 },
        .{ "KC_LANGUAGE_8",          0 },
        .{ "KC_LANGUAGE_9",          0 },
        .{ "KC_ALTERNATE_ERASE",     0 },                      .{ "KC_ERAS", 0 },
        .{ "KC_SYSTEM_REQUEST",      0 },                      .{ "KC_SYRQ", 0 },
        .{ "KC_CANCEL",              c.VK_CANCEL },            .{ "KC_CNCL", c.VK_CANCEL },
        .{ "KC_CLEAR",               c.VK_CLEAR },             .{ "KC_CLR", c.VK_CLEAR },
        .{ "KC_PRIOR",               0 },                      .{ "KC_PRIR", 0 },
        .{ "KC_SEPARATOR",           0 },                      .{ "KC_SEPR", 0 },
        .{ "KC_OUT",                 0 },
        .{ "KC_OPER",                0 },
        .{ "KC_CLEAR_AGAIN",         0 },                      .{ "KC_CLAG", 0 },
        .{ "KC_CRSEL",               c.VK_CRSEL },             .{ "KC_CRSL", c.VK_CRSEL },
        .{ "KC_EXSEL",               c.VK_EXSEL },             .{ "KC_EXSL", c.VK_EXSEL },
        .{ "KC_SYSTEM_POWER",        0 },                      .{ "KC_PWR", 0 },
        .{ "KC_SYSTEM_SLEEP",        0 },                      .{ "KC_SLEP", 0 },
        .{ "KC_SYSTEM_WAKE",         0 },                      .{ "KC_WAKE", 0 },
        .{ "KC_AUDIO_MUTE",          c.VK_VOLUME_MUTE },       .{ "KC_MUTE", c.VK_VOLUME_MUTE },
        .{ "KC_AUDIO_VOL_UP",        c.VK_VOLUME_UP },         .{ "KC_VOLU", c.VK_VOLUME_UP },
        .{ "KC_AUDIO_VOL_DOWN",      c.VK_VOLUME_DOWN },       .{ "KC_VOLD", c.VK_VOLUME_DOWN },
        .{ "KC_MEDIA_NEXT_TRACK",    c.VK_MEDIA_NEXT_TRACK },  .{ "KC_MNXT", c.VK_MEDIA_NEXT_TRACK },
        .{ "KC_MEDIA_PREV_TRACK",    c.VK_MEDIA_PREV_TRACK },  .{ "KC_MPRV", c.VK_MEDIA_PREV_TRACK },
        .{ "KC_MEDIA_STOP",          c.VK_MEDIA_STOP },        .{ "KC_MSTP", c.VK_MEDIA_STOP },
        .{ "KC_MEDIA_PLAY_PAUSE",    c.VK_MEDIA_PLAY_PAUSE },  .{ "KC_MPLY", c.VK_MEDIA_PLAY_PAUSE },
        .{ "KC_MEDIA_SELECT",        c.VK_LAUNCH_MEDIA_SELECT }, .{ "KC_MSEL", c.VK_LAUNCH_MEDIA_SELECT },
        .{ "KC_MEDIA_EJECT",         0 },                      .{ "KC_EJCT", 0 },
        .{ "KC_MAIL",                c.VK_LAUNCH_MAIL },
        .{ "KC_CALCULATOR",          0 },                      .{ "KC_CALC", 0 },
        .{ "KC_MY_COMPUTER",         0 },                      .{ "KC_MYCM", 0 },
        .{ "KC_WWW_SEARCH",          c.VK_BROWSER_SEARCH },
        .{ "KC_WWW_HOME",            c.VK_BROWSER_HOME },      .{ "KC_WHOM", c.VK_BROWSER_HOME },
        .{ "KC_WWW_BACK",            c.VK_BROWSER_BACK },      .{ "KC_WBAK", c.VK_BROWSER_BACK },
        .{ "KC_WWW_FORWARD",         c.VK_BROWSER_FORWARD },   .{ "KC_WFWD", c.VK_BROWSER_FORWARD },
        .{ "KC_WWW_STOP",            c.VK_BROWSER_STOP },      .{ "KC_WSTP", c.VK_BROWSER_STOP },
        .{ "KC_WWW_REFRESH",         c.VK_BROWSER_REFRESH },   .{ "KC_WREF", c.VK_BROWSER_REFRESH },
        .{ "KC_WWW_FAVORITES",       c.VK_BROWSER_FAVORITES }, .{ "KC_WFAV", c.VK_BROWSER_FAVORITES },
        .{ "KC_MEDIA_FAST_FORWARD",  0 },                      .{ "KC_MFFD", 0 },
        .{ "KC_MEDIA_REWIND",        0 },                      .{ "KC_MRWD", 0 },
        .{ "KC_BRIGHTNESS_UP",       0 },                      .{ "KC_BRIU", 0 },
        .{ "KC_BRIGHTNESS_DOWN",     0 },                      .{ "KC_BRID", 0 },
        .{ "KC_CONTROL_PANEL",       0 },                      .{ "KC_CPNL", 0 },
        .{ "KC_ASSISTANT",           0 },                      .{ "KC_ASST", 0 },
        .{ "KC_MISSION_CONTROL",     0 },                      .{ "KC_MCTL", 0 },
        .{ "KC_LAUNCHPAD",           0 },                      .{ "KC_LPAD", 0 },
        .{ "KC_LEFT_CTRL",           c.VK_LCONTROL},           .{ "KC_LCTL", c.VK_LCONTROL },
        .{ "KC_LEFT_SHIFT",          c.VK_LSHIFT },            .{ "KC_LSFT", c.VK_LSHIFT },
        .{ "KC_LEFT_ALT",            c.VK_LMENU },             .{ "KC_LALT", c.VK_LMENU },    .{ "KC_LOPT", c.VK_LMENU },
        .{ "KC_LEFT_GUI",            c.VK_LWIN },              .{ "KC_LGUI", c.VK_LWIN },     .{ "KC_LCMD", c.VK_LWIN },   .{ "KC_LWIN", c.VK_LWIN },
        .{ "KC_RIGHT_CTRL",          c.VK_RCONTROL },          .{ "KC_RCTL", c.VK_RCONTROL },
        .{ "KC_RIGHT_SHIFT",         c.VK_RSHIFT },            .{ "KC_RSFT", c.VK_RSHIFT },
        .{ "KC_RIGHT_ALT",           c.VK_RMENU },             .{ "KC_RALT", c.VK_RMENU },    .{ "KC_ROPT", c.VK_RMENU },  .{ "KC_ALGR", c.VK_RMENU },
        .{ "KC_RIGHT_GUI",           c.VK_RWIN },              .{ "KC_RGUI", c.VK_RWIN },     .{ "KC_RCMD", c.VK_RWIN },   .{ "KC_RWIN", c.VK_RWIN },
        // zig fmt: on
    };
    break :blk l;
    }
    else @compileError("Unsupported platform");
};

pub const labels_lookup = std.StaticStringMap(usize).initComptime(layout_labels_lookup_slice);

