const std = @import("std");
const l = @cImport({
    @cInclude("linux/input-event-codes.h");
});

const LayoutLabelsLookupKV = struct { []const u8, usize };
const layout_labels_lookup_slice = [_]LayoutLabelsLookupKV{
    // zig fmt: off
    .{ "KC_NO",                  l.KEY_RESERVED },
    .{ "KC_TRANSPARENT",         l.KEY_RESERVED },
    .{ "KC_A",                   l.KEY_A },
    .{ "KC_B",                   l.KEY_B },
    .{ "KC_C",                   l.KEY_C },
    .{ "KC_D",                   l.KEY_D },
    .{ "KC_E",                   l.KEY_E },
    .{ "KC_F",                   l.KEY_F },
    .{ "KC_G",                   l.KEY_G },
    .{ "KC_H",                   l.KEY_H },
    .{ "KC_I",                   l.KEY_I },
    .{ "KC_J",                   l.KEY_J },
    .{ "KC_K",                   l.KEY_K },
    .{ "KC_L",                   l.KEY_L },
    .{ "KC_M",                   l.KEY_M },
    .{ "KC_N",                   l.KEY_N },
    .{ "KC_O",                   l.KEY_O },
    .{ "KC_P",                   l.KEY_P },
    .{ "KC_Q",                   l.KEY_Q },
    .{ "KC_R",                   l.KEY_R },
    .{ "KC_S",                   l.KEY_S },
    .{ "KC_T",                   l.KEY_T },
    .{ "KC_U",                   l.KEY_U },
    .{ "KC_V",                   l.KEY_V },
    .{ "KC_W",                   l.KEY_W },
    .{ "KC_X",                   l.KEY_X },
    .{ "KC_Y",                   l.KEY_Y },
    .{ "KC_Z",                   l.KEY_Z },
    .{ "KC_1",                   l.KEY_1 },
    .{ "KC_2",                   l.KEY_2 },
    .{ "KC_3",                   l.KEY_3 },
    .{ "KC_4",                   l.KEY_4 },
    .{ "KC_5",                   l.KEY_5 },
    .{ "KC_6",                   l.KEY_6 },
    .{ "KC_7",                   l.KEY_7 },
    .{ "KC_8",                   l.KEY_8 },
    .{ "KC_9",                   l.KEY_9 },
    .{ "KC_0",                   l.KEY_0 },
    .{ "KC_ENTER",               l.KEY_ENTER },            .{ "KC_ENT",  l.KEY_ENTER },      .{ "KC_RETURN", l.KEY_ENTER },    .{ "KC_RETN", l.KEY_ENTER },
    .{ "KC_ESCAPE",              l.KEY_ESC },              .{ "KC_ESC",  l.KEY_ESC },
    .{ "KC_BACKSPACE",           l.KEY_BACKSPACE },        .{ "KC_BSPC", l.KEY_BACKSPACE },
    .{ "KC_TAB",                 l.KEY_TAB },
    .{ "KC_SPACE",               l.KEY_SPACE },            .{ "KC_SPC",  l.KEY_SPACE },
    .{ "KC_MINUS",               l.KEY_MINUS },            .{ "KC_MINS", l.KEY_MINUS },
    .{ "KC_EQUAL",               l.KEY_EQUAL },            .{ "KC_EQL",  l.KEY_EQUAL },
    .{ "KC_LEFT_BRACKET",        l.KEY_LEFTBRACE },        .{ "KC_LBRC", l.KEY_LEFTBRACE },
    .{ "KC_RIGHT_BRACKET",       l.KEY_RIGHTBRACE },       .{ "KC_RBRC", l.KEY_RIGHTBRACE },
    .{ "KC_BACKSLASH",           l.KEY_BACKSLASH },        .{ "KC_BSLS", l.KEY_BACKSLASH },
    .{ "KC_NONUS_HASH",          l.KEY_102ND },            .{ "KC_NUHS", l.KEY_102ND },
    .{ "KC_SEMICOLON",           l.KEY_SEMICOLON },        .{ "KC_SCLN", l.KEY_SEMICOLON },
    .{ "KC_QUOTE",               l.KEY_APOSTROPHE },       .{ "KC_QUOT", l.KEY_APOSTROPHE },
    .{ "KC_GRAVE",               l.KEY_GRAVE },            .{ "KC_GRV",  l.KEY_GRAVE },
    .{ "KC_COMMA",               l.KEY_COMMA },            .{ "KC_COMM", l.KEY_COMMA },
    .{ "KC_DOT",                 l.KEY_DOT },
    .{ "KC_SLASH",               l.KEY_SLASH },            .{ "KC_SLSH", l.KEY_SLASH },
    .{ "KC_CAPS_LOCK",           l.KEY_CAPSLOCK },         .{ "KC_CAPS", l.KEY_CAPSLOCK },
    .{ "KC_F1",                  l.KEY_F1 },
    .{ "KC_F2",                  l.KEY_F2 },
    .{ "KC_F3",                  l.KEY_F3 },
    .{ "KC_F4",                  l.KEY_F4 },
    .{ "KC_F5",                  l.KEY_F5 },
    .{ "KC_F6",                  l.KEY_F6 },
    .{ "KC_F7",                  l.KEY_F7 },
    .{ "KC_F8",                  l.KEY_F8 },
    .{ "KC_F9",                  l.KEY_F9 },
    .{ "KC_F10",                 l.KEY_F10 },
    .{ "KC_F11",                 l.KEY_F11 },
    .{ "KC_F12",                 l.KEY_F12 },
    .{ "KC_PRINT_SCREEN",        l.KEY_SYSRQ },            .{ "KC_PSCR", l.KEY_SYSRQ },
    .{ "KC_SCROLL_LOCK",         l.KEY_SCREENLOCK },       .{ "KC_SCRL", l.KEY_SCROLLLOCK }, .{ "KC_BRMD", l.KEY_SCREENLOCK },
    .{ "KC_PAUSE",               l.KEY_PAUSE },            .{ "KC_PAUS", l.KEY_PAUSE },      .{ "KC_BRK",  l.KEY_PAUSE },      .{ "KC_BRMU", l.KEY_PAUSE },
    .{ "KC_INSERT",              l.KEY_INSERT },           .{ "KC_INS",  l.KEY_INSERT },
    .{ "KC_HOME",                l.KEY_HOME },
    .{ "KC_PAGE_UP",             l.KEY_PAGEUP },           .{ "KC_PGUP", l.KEY_PAGEUP },
    .{ "KC_DELETE",              l.KEY_DELETE },           .{ "KC_DEL",  l.KEY_DELETE },
    .{ "KC_END",                 l.KEY_END },
    .{ "KC_PAGE_DOWN",           l.KEY_PAGEDOWN },         .{ "KC_PGDN", l.KEY_PAGEDOWN },
    .{ "KC_RIGHT",               l.KEY_RIGHT },            .{ "KC_RGHT", l.KEY_RIGHT },
    .{ "KC_LEFT",                l.KEY_LEFT },
    .{ "KC_DOWN",                l.KEY_DOWN },
    .{ "KC_UP",                  l.KEY_UP },
    .{ "KC_NUM_LOCK",            l.KEY_NUMLOCK },          .{ "KC_NUM",  l.KEY_NUMLOCK },
    .{ "KC_KP_SLASH",            l.KEY_KPSLASH },          .{ "KC_PSLS", l.KEY_KPSLASH },
    .{ "KC_KP_ASTERISK",         l.KEY_KPASTERISK },       .{ "KC_PAST", l.KEY_KPASTERISK },
    .{ "KC_KP_MINUS",            l.KEY_KPMINUS },
    .{ "KC_PMNS",                l.KEY_KPMINUS },
    .{ "KC_KP_PLUS",             l.KEY_KPPLUS },
    .{ "KC_PPLS",                l.KEY_KPPLUS },
    .{ "KC_KP_ENTER",            l.KEY_KPENTER },
    .{ "KC_PENT",                l.KEY_KPENTER },
    .{ "KC_KP_1",                l.KEY_KP1 },              .{ "KC_P1",   l.KEY_KP1 },
    .{ "KC_KP_2",                l.KEY_KP2 },              .{ "KC_P2",   l.KEY_KP2 },
    .{ "KC_KP_3",                l.KEY_KP3 },              .{ "KC_P3",   l.KEY_KP3 },
    .{ "KC_KP_4",                l.KEY_KP4 },              .{ "KC_P4",   l.KEY_KP4 },
    .{ "KC_KP_5",                l.KEY_KP5 },              .{ "KC_P5",   l.KEY_KP5 },
    .{ "KC_KP_6",                l.KEY_KP6 },              .{ "KC_P6",   l.KEY_KP6 },
    .{ "KC_KP_7",                l.KEY_KP7 },              .{ "KC_P7",   l.KEY_KP7 },
    .{ "KC_KP_8",                l.KEY_KP8 },              .{ "KC_P8",   l.KEY_KP8 },
    .{ "KC_KP_9",                l.KEY_KP9 },              .{ "KC_P9",   l.KEY_KP9 },
    .{ "KC_KP_0",                l.KEY_KP0 },              .{ "KC_P0",   l.KEY_KP0 },
    .{ "KC_KP_DOT",              l.KEY_KPDOT },            .{ "KC_PDOT", l.KEY_KPDOT },
    .{ "KC_NONUS_BACKSLASH",     l.KEY_BACKSLASH },        .{ "KC_NUBS", l.KEY_BACKSLASH },
    .{ "KC_APPLICATION",         l.KEY_COMPOSE },          .{ "KC_APP",  l.KEY_COMPOSE },
    .{ "KC_KB_POWER",            0 },
    .{ "KC_KP_EQUAL",            l.KEY_KPEQUAL },          .{ "KC_PEQL", l.KEY_KPEQUAL },
    .{ "KC_F13",                 l.KEY_F13 },
    .{ "KC_F14",                 l.KEY_F14 },
    .{ "KC_F15",                 l.KEY_F15 },
    .{ "KC_F16",                 l.KEY_F16 },
    .{ "KC_F17",                 l.KEY_F17 },
    .{ "KC_F18",                 l.KEY_F18 },
    .{ "KC_F19",                 l.KEY_F19 },
    .{ "KC_F20",                 l.KEY_F20 },
    .{ "KC_F21",                 l.KEY_F21 },
    .{ "KC_F22",                 l.KEY_F22 },
    .{ "KC_F23",                 l.KEY_F23 },
    .{ "KC_F24",                 l.KEY_F24 },
    .{ "KC_EXECUTE",             0 },                      .{ "KC_EXEC", 0 },
    .{ "KC_HELP",                l.KEY_HELP },
    .{ "KC_MENU",                l.KEY_MENU },
    .{ "KC_SELECT",              l.KEY_SELECT },           .{ "KC_SLCT", l.KEY_SELECT },
    .{ "KC_STOP",                l.KEY_STOP },
    .{ "KC_AGAIN",               l.KEY_AGAIN },            .{ "KC_AGIN", l.KEY_AGAIN },
    .{ "KC_UNDO",                l.KEY_UNDO },
    .{ "KC_CUT",                 l.KEY_CUT },
    .{ "KC_COPY",                l.KEY_COPY },
    .{ "KC_PASTE",               l.KEY_PASTE },            .{ "KC_PSTE", l.KEY_PASTE },
    .{ "KC_FIND",                l.KEY_FIND },
    .{ "KC_KB_MUTE",             l.KEY_MUTE },
    .{ "KC_KB_VOLUME_UP",        l.KEY_VOLUMEUP },
    .{ "KC_KB_VOLUME_DOWN",      l.KEY_VOLUMEDOWN },
    .{ "KC_LOCKING_CAPS_LOCK",   0 },                      .{ "KC_LCAP", 0 },
    .{ "KC_LOCKING_NUM_LOCK",    0 },                      .{ "KC_LNUM", 0 },
    .{ "KC_LOCKING_SCROLL_LOCK", 0 },                      .{ "KC_LSCR", 0 },
    .{ "KC_KP_COMMA",            l.KEY_KPCOMMA },          .{ "KC_PCMM", l.KEY_KPCOMMA },
    .{ "KC_KP_EQUAL_AS400",      0 },
    .{ "KC_INTERNATIONAL_1",     l.KEY_RO },               .{ "KC_INT1", l.KEY_RO },
    .{ "KC_INTERNATIONAL_2",     l.KEY_KATAKANAHIRAGANA }, .{ "KC_INT2", l.KEY_KATAKANAHIRAGANA },
    .{ "KC_INTERNATIONAL_3",     l.KEY_YEN },              .{ "KC_INT3", l.KEY_YEN },
    .{ "KC_INTERNATIONAL_4",     l.KEY_HENKAN },           .{ "KC_INT4", l.KEY_HENKAN },
    .{ "KC_INTERNATIONAL_5",     l.KEY_MUHENKAN },         .{ "KC_INT5", l.KEY_MUHENKAN },
    .{ "KC_INTERNATIONAL_6",     l.KEY_KPJPCOMMA },        .{ "KC_INT6", l.KEY_KPJPCOMMA },
    .{ "KC_INTERNATIONAL_7",     0 },
    .{ "KC_INTERNATIONAL_8",     0 },
    .{ "KC_INTERNATIONAL_9",     0 },
    .{ "KC_LANGUAGE_1",          l.KEY_HANGEUL },          .{ "KC_LNG1", l.KEY_HANGEUL },
    .{ "KC_LANGUAGE_2",          l.KEY_HANJA },            .{ "KC_LNG2", l.KEY_HANJA },
    .{ "KC_LANGUAGE_3",          l.KEY_KATAKANA },         .{ "KC_LNG3", l.KEY_KATAKANA },
    .{ "KC_LANGUAGE_4",          l.KEY_HIRAGANA },         .{ "KC_LNG4", l.KEY_HIRAGANA },
    .{ "KC_LANGUAGE_5",          l.KEY_ZENKAKUHANKAKU },   .{ "KC_LNG5", l.KEY_ZENKAKUHANKAKU },
    .{ "KC_LANGUAGE_6",          0 },
    .{ "KC_LANGUAGE_7",          0 },
    .{ "KC_LANGUAGE_8",          0 },
    .{ "KC_LANGUAGE_9",          0 },
    .{ "KC_ALTERNATE_ERASE",     0 },                      .{ "KC_ERAS", 0 },
    .{ "KC_SYSTEM_REQUEST",      l.KEY_SYSRQ },            .{ "KC_SYRQ", l.KEY_SYSRQ },
    .{ "KC_CANCEL",              0 },                      .{ "KC_CNCL", 0 },
    .{ "KC_CLEAR",               l.KEY_CLEAR },            .{ "KC_CLR",  l.KEY_CLEAR },
    .{ "KC_PRIOR",               0 },                      .{ "KC_PRIR", 0 },
    .{ "KC_SEPARATOR",           0 },                      .{ "KC_SEPR", 0 },
    .{ "KC_OUT",                 0 },
    .{ "KC_OPER",                0 },
    .{ "KC_CLEAR_AGAIN",         0 },                      .{ "KC_CLAG", 0 },
    .{ "KC_CRSEL",               0 },                      .{ "KC_CRSL", 0 },
    .{ "KC_EXSEL",               0 },                      .{ "KC_EXSL", 0 },
    .{ "KC_SYSTEM_POWER",        l.KEY_POWER },            .{ "KC_PWR",  l.KEY_POWER },
    .{ "KC_SYSTEM_SLEEP",        l.KEY_SLEEP },            .{ "KC_SLEP", l.KEY_SLEEP },
    .{ "KC_SYSTEM_WAKE",         l.KEY_WAKEUP },           .{ "KC_WAKE", l.KEY_WAKEUP },
    .{ "KC_AUDIO_MUTE",          l.KEY_MUTE },             .{ "KC_MUTE", l.KEY_MUTE },
    .{ "KC_AUDIO_VOL_UP",        l.KEY_VOLUMEUP },         .{ "KC_VOLU", l.KEY_VOLUMEUP },
    .{ "KC_AUDIO_VOL_DOWN",      l.KEY_VOLUMEDOWN },       .{ "KC_VOLD", l.KEY_VOLUMEDOWN },
    .{ "KC_MEDIA_NEXT_TRACK",    l.KEY_NEXTSONG },         .{ "KC_MNXT", l.KEY_NEXTSONG },
    .{ "KC_MEDIA_PREV_TRACK",    l.KEY_PREVIOUSSONG },     .{ "KC_MPRV", l.KEY_PREVIOUSSONG },
    .{ "KC_MEDIA_STOP",          l.KEY_STOPCD },           .{ "KC_MSTP", l.KEY_STOPCD },
    .{ "KC_MEDIA_PLAY_PAUSE",    l.KEY_PLAYPAUSE },        .{ "KC_MPLY", l.KEY_PLAYPAUSE },
    .{ "KC_MEDIA_SELECT",        0 },                      .{ "KC_MSEL", 0 },
    .{ "KC_MEDIA_EJECT",         l.KEY_EJECTCD },          .{ "KC_EJCT", l.KEY_EJECTCD },
    .{ "KC_MAIL",                l.KEY_MAIL },
    .{ "KC_CALCULATOR",          l.KEY_CALC },             .{ "KC_CALC", l.KEY_CALC },
    .{ "KC_MY_COMPUTER",         l.KEY_COMPUTER },         .{ "KC_MYCM", l.KEY_COMPUTER },
    .{ "KC_WWW_SEARCH",          l.KEY_FIND },             .{ "KC_WSCH", l.KEY_FIND },
    .{ "KC_WWW_HOME",            l.KEY_HOMEPAGE },         .{ "KC_WHOM", l.KEY_HOMEPAGE },
    .{ "KC_WWW_BACK",            l.KEY_BACK },             .{ "KC_WBAK", l.KEY_BACK },
    .{ "KC_WWW_FORWARD",         l.KEY_FORWARD },          .{ "KC_WFWD", l.KEY_FORWARD },
    .{ "KC_WWW_STOP",            l.KEY_STOP },             .{ "KC_WSTP", l.KEY_STOP },
    .{ "KC_WWW_REFRESH",         l.KEY_REFRESH },          .{ "KC_WREF", l.KEY_REFRESH },
    .{ "KC_WWW_FAVORITES",       l.KEY_BOOKMARKS },        .{ "KC_WFAV", l.KEY_BOOKMARKS },
    .{ "KC_MEDIA_FAST_FORWARD",  l.KEY_FASTFORWARD },      .{ "KC_MFFD", l.KEY_FASTFORWARD },
    .{ "KC_MEDIA_REWIND",        0 },                      .{ "KC_MRWD", 0 },
    .{ "KC_BRIGHTNESS_UP",       l.KEY_BRIGHTNESSUP },     .{ "KC_BRIU", l.KEY_BRIGHTNESSUP },
    .{ "KC_BRIGHTNESS_DOWN",     l.KEY_BRIGHTNESSDOWN },   .{ "KC_BRID", l.KEY_BRIGHTNESSDOWN },
    .{ "KC_CONTROL_PANEL",       0 },                      .{ "KC_CPNL", 0 },
    .{ "KC_ASSISTANT",           0 },                      .{ "KC_ASST", 0 },
    .{ "KC_MISSION_CONTROL",     0 },                      .{ "KC_MCTL", 0 },
    .{ "KC_LAUNCHPAD",           0 },                      .{ "KC_LPAD", 0 },
    .{ "KC_LEFT_CTRL",           l.KEY_LEFTCTRL },         .{ "KC_LCTL", l.KEY_LEFTCTRL },
    .{ "KC_LEFT_SHIFT",          l.KEY_LEFTSHIFT },        .{ "KC_LSFT", l.KEY_LEFTSHIFT },
    .{ "KC_LEFT_ALT",            l.KEY_LEFTALT },          .{ "KC_LALT", l.KEY_LEFTALT },    .{ "KC_LOPT", l.KEY_LEFTALT },
    .{ "KC_LEFT_GUI",            l.KEY_LEFTMETA },         .{ "KC_LGUI", l.KEY_LEFTMETA },   .{ "KC_LCMD", l.KEY_LEFTMETA },   .{ "KC_LWIN", l.KEY_LEFTMETA },
    .{ "KC_RIGHT_CTRL",          l.KEY_RIGHTCTRL },        .{ "KC_RCTL", l.KEY_RIGHTCTRL },
    .{ "KC_RIGHT_SHIFT",         l.KEY_RIGHTSHIFT },       .{ "KC_RSFT", l.KEY_RIGHTSHIFT },
    .{ "KC_RIGHT_ALT",           l.KEY_RIGHTALT },         .{ "KC_RALT", l.KEY_RIGHTALT },   .{ "KC_ROPT", l.KEY_RIGHTALT },   .{ "KC_ALGR", l.KEY_RIGHTALT },
    .{ "KC_RIGHT_GUI",           l.KEY_RIGHTMETA },        .{ "KC_RGUI", l.KEY_RIGHTMETA },  .{ "KC_RCMD", l.KEY_RIGHTMETA },  .{ "KC_RWIN", l.KEY_RIGHTMETA },
    // zig fmt: on
};
pub const labels_lookup = std.StaticStringMap(usize).initComptime(layout_labels_lookup_slice);

