name: Build & Test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        zig_version:
          - latest
          - master
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ matrix.zig_version }}
      - run: zig build test
